#!/usr/bin/osascript
-- ============================================================================
-- Count the Evernote notes that match a given query string
--
-- Examples:
--
--    count-notes "tag:current"
--    count-notes "intitle:diary"
--    count-notes "intitle:Start tag:current"
--
-- Note that the query string must be enclosed in quotes if it contains spaces
-- ============================================================================
on run argv
    tell application "Evernote"
        set query to item 1 of argv
        set nlist to (find notes query)
        do shell script "echo notes: " & (count of nlist)
    end tell
end run