#!/usr/bin/osascript
-- ============================================================================
-- Shift tags on notes for today and yesterday
--
-- Usage: daily-twiddle
--
-- It is safe to run this script multiple times in the same day.
-- ============================================================================
on run argv
    set cwd to (do shell script "pwd")
    set fpath to cwd & "/library.scpt"
    set lib to load script POSIX file fpath

    set today_title to lib's diary_title(current date)
    set yesterdate to (current date) - 24*3600
    set yester_title to lib's diary_title(yesterdate)

    tell application "Evernote"
        set query to "intitle:" & yester_title
        set ylist to (find notes query)
        if (count of ylist) is greater than 1 then
            display dialog "'" & yester_title & "' matches multiple notes"
        end if

        set query to "intitle:" & today_title
        set tlist to (find notes query)
        if (count of tlist) is greater than 1 then
            display dialog "'" & today_title & "' matches multiple notes"
        end if
    end tell
end run
