#!/usr/bin/osascript
-- ============================================================================
-- Shift tags on notes for today and yesterday
--
-- Usage: daily-twiddle
--
-- It is safe to run this script multiple times in the same day.
-- ============================================================================
on run argv
    set cwd to (do shell script "pwd")
    set fpath to cwd & "/library.scpt"
    set lib to load script POSIX file fpath

    set today_title to lib's diary_title(current date)
    set yesterdate to (current date) - 24*3600
    set yester_title to lib's diary_title(yesterdate)

    tell application "Evernote"
        set query to "intitle:" & yester_title
        set nlist to (find notes query)
        if (count of nlist) is greater than 1 then
            do shell script "echo " & yester_title & " matches multiple notes"
        else
            set yester_note to item 1 of nlist
            set taglist to (tags of yester_note)
            lib's safe_rmtag(yester_note, tag named "today")
            lib's safe_addtag(yester_note, tag named "past")
        end if

        set query to "intitle:" & today_title
        set nlist to (find notes query)
        if (count of nlist) is greater than 1 then
            do shell script "echo " & today_title & " matches multiple notes"
        else
            set today_note to item 1 of nlist
            lib's safe_rmtag(today_note, tag named "future")
            lib's safe_addtag(today_note, tag named "today")
            lib's safe_addtag(today_note, tag named "current")
        end if
    end tell
end run
