#!/usr/bin/osascript

on run argv
    tell application "Evernote"
        set query_string to item 1 of argv
        set note_list to (find notes query_string)
        repeat with my_note in note_list
            set my_win to open note window with my_note
            close my_win
            delete my_note
        end repeat
        set note_count to (count of note_list)
        do shell script "echo " & note_count & " notes deleted"
    end tell
end run
